/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tama.basicswing;

import javax.swing.JOptionPane;

/**
 *
 * @author Pongo
 */
public class ConvertStrDouble extends javax.swing.JFrame {

    /**
     * Creates new form ConvertStrDouble
     */
    public ConvertStrDouble() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTinggi2 = new javax.swing.JLabel();
        txtTinggi2 = new javax.swing.JTextField();
        lblTinggi = new javax.swing.JLabel();
        btnHitung = new javax.swing.JButton();
        txtTinggi = new javax.swing.JTextField();
        lblJari = new javax.swing.JLabel();
        txtJari = new javax.swing.JTextField();
        lblVolume = new javax.swing.JLabel();
        txtVolume = new javax.swing.JTextField();

        lblTinggi2.setFont(new java.awt.Font("JetBrains Mono", 1, 14)); // NOI18N
        lblTinggi2.setText("Tinggi Tabung");

        txtTinggi2.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("String to Double");
        setName("StringDouble"); // NOI18N

        lblTinggi.setFont(new java.awt.Font("JetBrains Mono", 1, 14)); // NOI18N
        lblTinggi.setText("Tinggi Tabung");

        btnHitung.setText("HITUNG");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        txtTinggi.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N

        lblJari.setFont(new java.awt.Font("JetBrains Mono", 1, 14)); // NOI18N
        lblJari.setText("Jari2 Tabung");

        txtJari.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N

        lblVolume.setFont(new java.awt.Font("JetBrains Mono", 1, 14)); // NOI18N
        lblVolume.setText("Volume Tabung");

        txtVolume.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTinggi, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJari, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHitung)
                    .addComponent(txtTinggi, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJari, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTinggi)
                    .addComponent(txtTinggi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJari)
                    .addComponent(txtJari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVolume)
                    .addComponent(txtVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(btnHitung)
                .addGap(34, 34, 34))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:
        try{
        double tinggi = Double.parseDouble(txtTinggi.getText().trim());
        double jari = Double.parseDouble(txtJari.getText().trim());

        if ((txtTinggi.getText().isEmpty() || txtTinggi.getText().isBlank() || txtTinggi.getText().contains(" ")) || (txtJari.getText().isEmpty() || txtJari.getText().isBlank() || txtTinggi.getText().contains(" "))) {
            JOptionPane.showMessageDialog(this, "Salah satu angka kosong", "Error", JOptionPane.INFORMATION_MESSAGE);
        } else if (tinggi == 0 || jari == 0) {
            JOptionPane.showMessageDialog(this, "Tidak boleh angka 0", "Message", JOptionPane.INFORMATION_MESSAGE);
            txtTinggi.setText("");
            txtJari.setText("");
            txtTinggi.requestFocus();
        } else {
            double volume = (22.0/7.0) * jari * jari * tinggi;
            txtVolume.setText(String.valueOf(volume));
        }
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error: " + e, "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnHitungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConvertStrDouble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConvertStrDouble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConvertStrDouble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConvertStrDouble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ConvertStrDouble().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private javax.swing.JLabel lblJari;
    private javax.swing.JLabel lblTinggi;
    private javax.swing.JLabel lblTinggi2;
    private javax.swing.JLabel lblVolume;
    private javax.swing.JTextField txtJari;
    private javax.swing.JTextField txtTinggi;
    private javax.swing.JTextField txtTinggi2;
    private javax.swing.JTextField txtVolume;
    // End of variables declaration//GEN-END:variables
}
