/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tama.basicswing;

/**
 *
 * @author Pongo
 */
public class TestOpen extends javax.swing.JFrame {

    /**
     * Creates new form TestOpen
     */
    public TestOpen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btnShowMessage = new javax.swing.JButton();
        btnVolume = new javax.swing.JButton();
        btnVolTabung = new javax.swing.JButton();
        btnCek = new javax.swing.JButton();
        btnGender = new javax.swing.JButton();
        btnTravel = new javax.swing.JButton();
        btnGrade = new javax.swing.JButton();
        btnDaftar = new javax.swing.JButton();
        btnTable = new javax.swing.JButton();
        btnNotebook = new javax.swing.JButton();
        btnVilla = new javax.swing.JButton();
        btnLoop = new javax.swing.JButton();
        btnPangkat = new javax.swing.JButton();
        btnTestInput = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OpenForm");
        setName("TestOpen"); // NOI18N

        jButton1.setFont(new java.awt.Font("JetBrains Mono", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 51, 51));
        jButton1.setText("DISPLAY TEXT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnShowMessage.setBackground(new java.awt.Color(255, 204, 204));
        btnShowMessage.setFont(new java.awt.Font("JetBrains Mono", 1, 12)); // NOI18N
        btnShowMessage.setForeground(new java.awt.Color(255, 51, 51));
        btnShowMessage.setText("SHOW MESSAGE");
        btnShowMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowMessageActionPerformed(evt);
            }
        });

        btnVolume.setBackground(new java.awt.Color(255, 204, 204));
        btnVolume.setFont(new java.awt.Font("JetBrains Mono", 1, 12)); // NOI18N
        btnVolume.setForeground(new java.awt.Color(255, 51, 51));
        btnVolume.setText("Volume Tabung");
        btnVolume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolumeActionPerformed(evt);
            }
        });

        btnVolTabung.setBackground(new java.awt.Color(255, 204, 204));
        btnVolTabung.setFont(new java.awt.Font("JetBrains Mono", 1, 12)); // NOI18N
        btnVolTabung.setForeground(new java.awt.Color(255, 51, 51));
        btnVolTabung.setText("VOLUME Tabung");
        btnVolTabung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolTabungActionPerformed(evt);
            }
        });

        btnCek.setBackground(new java.awt.Color(255, 204, 204));
        btnCek.setFont(new java.awt.Font("JetBrains Mono", 1, 12)); // NOI18N
        btnCek.setForeground(new java.awt.Color(255, 51, 51));
        btnCek.setText("Tiket Bioskop");
        btnCek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekActionPerformed(evt);
            }
        });

        btnGender.setBackground(new java.awt.Color(255, 204, 204));
        btnGender.setFont(new java.awt.Font("JetBrains Mono", 1, 12)); // NOI18N
        btnGender.setForeground(new java.awt.Color(255, 51, 51));
        btnGender.setText("Check Gender");
        btnGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenderActionPerformed(evt);
            }
        });

        btnTravel.setBackground(new java.awt.Color(255, 204, 204));
        btnTravel.setFont(new java.awt.Font("JetBrains Mono", 1, 12)); // NOI18N
        btnTravel.setForeground(new java.awt.Color(255, 51, 51));
        btnTravel.setText("Check Client");
        btnTravel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTravelActionPerformed(evt);
            }
        });

        btnGrade.setBackground(new java.awt.Color(255, 204, 204));
        btnGrade.setFont(new java.awt.Font("JetBrains Mono", 1, 12)); // NOI18N
        btnGrade.setForeground(new java.awt.Color(255, 51, 51));
        btnGrade.setText("Grade Rumah");
        btnGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGradeActionPerformed(evt);
            }
        });

        btnDaftar.setFont(new java.awt.Font("JetBrains Mono", 1, 12)); // NOI18N
        btnDaftar.setForeground(new java.awt.Color(255, 51, 51));
        btnDaftar.setText("Daftar Laptop");
        btnDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarActionPerformed(evt);
            }
        });

        btnTable.setBackground(new java.awt.Color(255, 204, 204));
        btnTable.setFont(new java.awt.Font("JetBrains Mono", 1, 12)); // NOI18N
        btnTable.setForeground(new java.awt.Color(255, 51, 51));
        btnTable.setText("Table Member");
        btnTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTableActionPerformed(evt);
            }
        });

        btnNotebook.setFont(new java.awt.Font("JetBrains Mono", 1, 12)); // NOI18N
        btnNotebook.setForeground(new java.awt.Color(255, 51, 51));
        btnNotebook.setText("Daftar Notebook");
        btnNotebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotebookActionPerformed(evt);
            }
        });

        btnVilla.setBackground(new java.awt.Color(255, 204, 204));
        btnVilla.setFont(new java.awt.Font("JetBrains Mono", 1, 12)); // NOI18N
        btnVilla.setForeground(new java.awt.Color(255, 51, 51));
        btnVilla.setText("Grade Villa");
        btnVilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVillaActionPerformed(evt);
            }
        });

        btnLoop.setBackground(new java.awt.Color(255, 204, 204));
        btnLoop.setFont(new java.awt.Font("JetBrains Mono", 1, 12)); // NOI18N
        btnLoop.setForeground(new java.awt.Color(255, 51, 51));
        btnLoop.setText("Looping Angka");
        btnLoop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoopActionPerformed(evt);
            }
        });

        btnPangkat.setBackground(new java.awt.Color(255, 204, 204));
        btnPangkat.setFont(new java.awt.Font("JetBrains Mono", 1, 12)); // NOI18N
        btnPangkat.setForeground(new java.awt.Color(255, 51, 51));
        btnPangkat.setText("Looping Pangkat");
        btnPangkat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPangkatActionPerformed(evt);
            }
        });

        btnTestInput.setFont(new java.awt.Font("JetBrains Mono", 1, 12)); // NOI18N
        btnTestInput.setForeground(new java.awt.Color(255, 51, 51));
        btnTestInput.setText("TEST INPUT");
        btnTestInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnVolume, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnShowMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVolTabung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTravel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDaftar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNotebook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGrade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVilla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLoop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPangkat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnTestInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnDaftar)
                    .addComponent(btnTestInput))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnShowMessage)
                    .addComponent(btnNotebook))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolume)
                    .addComponent(btnTable))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolTabung)
                    .addComponent(btnGrade))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCek)
                    .addComponent(btnVilla))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGender)
                    .addComponent(btnLoop))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTravel)
                    .addComponent(btnPangkat))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new TextsInput().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnShowMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowMessageActionPerformed
        // TODO add your handling code here:
        new ShowMessage().setVisible(true);
    }//GEN-LAST:event_btnShowMessageActionPerformed

    private void btnVolumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolumeActionPerformed
        // TODO add your handling code here:
        new ConvertStrInt().setVisible(true);
    }//GEN-LAST:event_btnVolumeActionPerformed

    private void btnVolTabungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolTabungActionPerformed
        // TODO add your handling code here:
        new ConvertStrDouble().setVisible(true);
    }//GEN-LAST:event_btnVolTabungActionPerformed

    private void btnCekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekActionPerformed
        // TODO add your handling code here:
        new TiketBioskop().setVisible(true);
    }//GEN-LAST:event_btnCekActionPerformed

    private void btnGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenderActionPerformed
        // TODO add your handling code here:
        new Gender().setVisible(true);
    }//GEN-LAST:event_btnGenderActionPerformed

    private void btnTravelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTravelActionPerformed
        // TODO add your handling code here:
        new Travel().setVisible(true);
    }//GEN-LAST:event_btnTravelActionPerformed

    private void btnGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGradeActionPerformed
        // TODO add your handling code here:
        new SewaRumah().setVisible(true);
    }//GEN-LAST:event_btnGradeActionPerformed

    private void btnDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarActionPerformed
        // TODO add your handling code here:
        new DaftarLaptop().setVisible(true);
    }//GEN-LAST:event_btnDaftarActionPerformed

    private void btnTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTableActionPerformed
        // TODO add your handling code here:
        new Member().setVisible(true);
    }//GEN-LAST:event_btnTableActionPerformed

    private void btnNotebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotebookActionPerformed
        // TODO add your handling code here:
        new DaftarNotebook().setVisible(true);
    }//GEN-LAST:event_btnNotebookActionPerformed

    private void btnVillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVillaActionPerformed
        // TODO add your handling code here:
        new SewaVilla().setVisible(true);
    }//GEN-LAST:event_btnVillaActionPerformed

    private void btnLoopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoopActionPerformed
        // TODO add your handling code here:
        new LoopAngka().setVisible(true);
    }//GEN-LAST:event_btnLoopActionPerformed

    private void btnPangkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPangkatActionPerformed
        // TODO add your handling code here:
        new LoopPangkat().setVisible(true);
    }//GEN-LAST:event_btnPangkatActionPerformed

    private void btnTestInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestInputActionPerformed
        // TODO add your handling code here:
        new Mahasiswa().setVisible(true);
    }//GEN-LAST:event_btnTestInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestOpen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestOpen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestOpen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestOpen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestOpen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCek;
    private javax.swing.JButton btnDaftar;
    private javax.swing.JButton btnGender;
    private javax.swing.JButton btnGrade;
    private javax.swing.JButton btnLoop;
    private javax.swing.JButton btnNotebook;
    private javax.swing.JButton btnPangkat;
    private javax.swing.JButton btnShowMessage;
    private javax.swing.JButton btnTable;
    private javax.swing.JButton btnTestInput;
    private javax.swing.JButton btnTravel;
    private javax.swing.JButton btnVilla;
    private javax.swing.JButton btnVolTabung;
    private javax.swing.JButton btnVolume;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
