/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tama.basicswing;

import com.mysql.cj.jdbc.MysqlDataSource;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import java.text.ParseException;
import java.text.SimpleDateFormat;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.xssf.usermodel.XSSFCellStyle;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author Pongo
 */
public class UploadDownload extends javax.swing.JFrame {

    /**
     * Creates new form UploadDownload
     */
    public UploadDownload() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUploadCSV = new javax.swing.JButton();
        btnDownloadCSV = new javax.swing.JButton();
        btnDownloadXLSX = new javax.swing.JButton();
        btnUploadXLSX = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnUploadCSV.setFont(new java.awt.Font("JetBrains Mono", 1, 14)); // NOI18N
        btnUploadCSV.setText("UPLOAD CSV");
        btnUploadCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadCSVActionPerformed(evt);
            }
        });

        btnDownloadCSV.setFont(new java.awt.Font("JetBrains Mono", 1, 14)); // NOI18N
        btnDownloadCSV.setText("DOWNLOAD CSV");
        btnDownloadCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadCSVActionPerformed(evt);
            }
        });

        btnDownloadXLSX.setFont(new java.awt.Font("JetBrains Mono", 1, 14)); // NOI18N
        btnDownloadXLSX.setText("DOWNLOAD EXCEL");
        btnDownloadXLSX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadXLSXActionPerformed(evt);
            }
        });

        btnUploadXLSX.setFont(new java.awt.Font("JetBrains Mono", 1, 14)); // NOI18N
        btnUploadXLSX.setText("UPLOAD EXCEL");
        btnUploadXLSX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadXLSXActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDownloadCSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUploadCSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDownloadXLSX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUploadXLSX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(btnDownloadCSV)
                .addGap(18, 18, 18)
                .addComponent(btnUploadCSV)
                .addGap(31, 31, 31)
                .addComponent(btnDownloadXLSX)
                .addGap(18, 18, 18)
                .addComponent(btnUploadXLSX)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDownloadCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadCSVActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File("Download"));
        fileChooser.setSelectedFile(new File("customer_data.csv"));
        int result = fileChooser.showSaveDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            try {
                exportToCSV(selectedFile);
                JOptionPane.showMessageDialog(this, "Data berhasil di-download!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnDownloadCSVActionPerformed

    private void exportToCSV(File file) throws IOException, SQLException {
        MysqlDataSource dataSource = new MysqlDataSource();
        dataSource.setUser("rangga");
        dataSource.setPassword("rangga");
        dataSource.setServerName("localhost");
        dataSource.setDatabaseName("java_database");

        try (Connection conn = dataSource.getConnection(); BufferedWriter bw = new BufferedWriter(new FileWriter(file))) {

            String sql = "SELECT id, name, email, birth FROM Customer";
            try (Statement stmt = conn.createStatement(); ResultSet rs = stmt.executeQuery(sql)) {

                // Write header
                bw.write("id;name;email;birth");
                bw.newLine();

                // Write data
                while (rs.next()) {
                    StringBuilder sb = new StringBuilder();
                    sb.append(rs.getString("id")).append(";");
                    sb.append(rs.getString("name")).append(";");
                    sb.append(rs.getString("email")).append(";");
                    sb.append(formatDate(rs.getDate("birth")));
                    bw.write(sb.toString());
                    bw.newLine();
                }
            }
        }
    }

    private String formatDate(Date date) {
        if (date == null) {
            return "";
        }
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        return sdf.format(date);
    }

    private void btnUploadCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadCSVActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File("Upload"));
        int result = fileChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            try {
                processCSV(selectedFile);
                JOptionPane.showMessageDialog(this, "Data berhasil di-upload!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnUploadCSVActionPerformed

    private void processCSV(File file) throws IOException, SQLException, ParseException {
        MysqlDataSource dataSource = new MysqlDataSource();
        dataSource.setUser("rangga");
        dataSource.setPassword("rangga");
        dataSource.setServerName("localhost");
        dataSource.setDatabaseName("java_database");

        try (Connection conn = dataSource.getConnection(); BufferedReader br = new BufferedReader(new FileReader(file))) {

            String line;
            boolean isFirstLine = true;

            while ((line = br.readLine()) != null) {
                if (isFirstLine) {
                    isFirstLine = false;
                    continue;
                }

                String[] data = line.split(";");
                if (data.length != 4) {
                    throw new IOException("Invalid CSV format");
                }

                String sql = "INSERT INTO Customer (id, name, email, birth) VALUES (?, ?, ?, ?)";
                try (PreparedStatement pstmt = conn.prepareStatement(sql)) {
                    pstmt.setString(1, data[0].trim());
                    pstmt.setString(2, data[1].trim());
                    pstmt.setString(3, data[2].trim());
                    pstmt.setDate(4, convertToSqlDate(data[3].trim()));
                    pstmt.executeUpdate();
                }
            }
        }
    }

    private java.sql.Date convertToSqlDate(String dateString) throws ParseException {
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        java.util.Date parsed = format.parse(dateString);
        return new java.sql.Date(parsed.getTime());
    }

    private void btnDownloadXLSXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadXLSXActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File("Download"));
        fileChooser.setSelectedFile(new File("customer_data.xlsx"));
        int result = fileChooser.showSaveDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            if (!selectedFile.getName().toLowerCase().endsWith(".xlsx")) {
                selectedFile = new File(selectedFile.getParentFile(), selectedFile.getName() + ".xlsx");
            }
            processDataToExcel(selectedFile);
        }
    }//GEN-LAST:event_btnDownloadXLSXActionPerformed

    private void processDataToExcel(File file) {
        try (Connection conn = getConnection();
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery("SELECT id, name, email, birth FROM Customer");
             XSSFWorkbook workbook = new XSSFWorkbook()) {

            XSSFSheet sheet = workbook.createSheet("Customer Data");
            Row headerRow = sheet.createRow(0);
            headerRow.createCell(0).setCellValue("ID");
            headerRow.createCell(1).setCellValue("Name");
            headerRow.createCell(2).setCellValue("Email");
            headerRow.createCell(3).setCellValue("Birth");

            int rowNum = 1;
            while (rs.next()) {
                Row row = sheet.createRow(rowNum++);
                row.createCell(0).setCellValue(rs.getString("id"));
                row.createCell(1).setCellValue(rs.getString("name"));
                row.createCell(2).setCellValue(rs.getString("email"));
                row.createCell(3).setCellValue(rs.getDate("birth").toString());
            }

            // Set semicolon as column separator
            for (int i = 0; i < 4; i++) {
                sheet.setColumnWidth(i, 4000);
                XSSFCellStyle style = workbook.createCellStyle();
                style.setDataFormat(workbook.createDataFormat().getFormat("text;"));
                sheet.setDefaultColumnStyle(i, style);
            }

            try (FileOutputStream outputStream = new FileOutputStream(file)) {
                workbook.write(outputStream);
            }

            JOptionPane.showMessageDialog(this, "Data berhasil di-download ke file Excel.", "Sukses", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void btnUploadXLSXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadXLSXActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File("Upload"));
        int result = fileChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            processExcelFile(selectedFile);
        }
    }//GEN-LAST:event_btnUploadXLSXActionPerformed

    private void processExcelFile(File file) {
        try (FileInputStream fis = new FileInputStream(file); XSSFWorkbook workbook = new XSSFWorkbook(fis)) {

            XSSFSheet sheet = workbook.getSheetAt(0);
            Connection conn = getConnection();

            String sql = "INSERT INTO Customer (id, name, email, birth) VALUES (?, ?, ?, ?)";
            PreparedStatement pstmt = conn.prepareStatement(sql);

            for (Row row : sheet) {
                if (row.getRowNum() == 0) {
                    continue; // Skip header row
                }
                Cell idCell = row.getCell(0);
                Cell nameCell = row.getCell(1);
                Cell emailCell = row.getCell(2);
                Cell birthCell = row.getCell(3);

                pstmt.setString(1, idCell.getStringCellValue());
                pstmt.setString(2, nameCell.getStringCellValue());
                pstmt.setString(3, emailCell.getStringCellValue());
                pstmt.setDate(4, new java.sql.Date(birthCell.getDateCellValue().getTime()));

                pstmt.executeUpdate();
            }

            pstmt.close();
            conn.close();

            JOptionPane.showMessageDialog(this, "Data berhasil di-upload ke database.", "Sukses", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private Connection getConnection() throws SQLException {
        String url = "jdbc:mysql://localhost:3306/java_database";
        String user = "rangga";
        String password = "rangga";
        return DriverManager.getConnection(url, user, password);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UploadDownload.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UploadDownload.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UploadDownload.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UploadDownload.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new UploadDownload().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDownloadCSV;
    private javax.swing.JButton btnDownloadXLSX;
    private javax.swing.JButton btnUploadCSV;
    private javax.swing.JButton btnUploadXLSX;
    // End of variables declaration//GEN-END:variables
}
